import { StyleSheet, Platform } from "react-native";

export const createStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    topBar: {
      paddingTop: Platform.OS === "ios" ? 45 : 28,
      paddingHorizontal: 14,
      paddingBottom: 12,
      minHeight: Platform.OS === "ios" ? 70 : 55,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
    searchBox: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      borderRadius: 18,
      paddingHorizontal: 14,
      paddingVertical: Platform.OS === "ios" ? 10 : 8,
      borderWidth: 1,
      gap: 8,
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      fontWeight: "400",
    },
    actionBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    tabs: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 12,
      gap: 8,
    },
    tabItem: {
      paddingHorizontal: 20,
      paddingVertical: 8,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    tabText: {
      fontSize: 15,
    },
    listContent: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 100,
      gap: 20,
      flexGrow: 1,
    },
    listAndFooter: {
      flexGrow: 1,
    },
    booksList: {
      gap: 10,
    },
    paginationSpacer: {
      flexGrow: 1,
    },
    paginationRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
      paddingVertical: 12,
      paddingHorizontal: 14,
    },
    pageIconBtn: {
      width: 40,
      height: 40,
      borderRadius: 12,
      borderWidth: 1,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOpacity: 0.08,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    pageInfoPill: {
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: 14,
      borderWidth: 1,
      minWidth: 100,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 1 },
      elevation: 1,
    },
    pageInfoText: {
      fontSize: 14,
      fontWeight: "700",
    },
    swipeActions: {
      width: 220,
      flexDirection: "row",
      height: "100%",
      borderRadius: 16,
      overflow: "hidden",
    },
    swipeBtn: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingHorizontal: 8,
    },
    swipeText: {
      fontSize: 11,
      fontWeight: "700",
      textAlign: "center",
    },
    bookCard: {
      flexDirection: "row",
      gap: 14,
      padding: 14,
      borderRadius: 16,
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
    cover: {
      width: 60,
      height: 80,
      borderRadius: 10,
      borderWidth: 1,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    bookInfo: {
      flex: 1,
      gap: 6,
      justifyContent: "space-between",
    },
    bookTitle: {
      fontSize: 16,
      fontWeight: "700",
      lineHeight: 22,
    },
    bookAuthor: {
      fontSize: 13,
      fontWeight: "500",
      opacity: 0.8,
    },
    bookFooter: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 4,
    },
    statusBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    statusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
    },
    statusText: {
      fontSize: 12,
      fontWeight: "600",
    },
    dueDate: {
      fontSize: 11,
      fontWeight: "500",
      opacity: 0.7,
      marginLeft: 4,
    },
    dueDateContainer: {
      flexDirection: "row",
      alignItems: "center",
    },
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 80,
      paddingHorizontal: 40,
    },
    emptyIconContainer: {
      width: 120,
      height: 120,
      borderRadius: 60,
      alignItems: "center",
      justifyContent: "center",
      opacity: 0.5,
      marginBottom: 20,
    },
    emptyText: {
      fontSize: 16,
      fontWeight: "600",
      textAlign: "center",
      marginBottom: 8,
    },
    emptySubtext: {
      fontSize: 14,
      textAlign: "center",
      opacity: 0.7,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 80,
    },
    loadingText: {
      fontSize: 14,
      marginTop: 12,
      fontWeight: "500",
    },
    loadMoreContainer: {
      paddingTop: 12,
      paddingBottom: 16,
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
    },
    loadMoreText: {
      fontSize: 13,
      fontWeight: "500",
    },
    endContainer: {
      paddingTop: 12,
      paddingBottom: 16,
      alignItems: "center",
      justifyContent: "center",
    },
    endText: {
      fontSize: 13,
      fontWeight: "500",
      opacity: 0.7,
    },
    retryButton: {
      marginTop: 16,
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    retryButtonText: {
      fontSize: 14,
      fontWeight: "600",
    },
    bookItemWrapper: {
      marginBottom: 10,
    },
    coverImage: {
      width: "100%",
      height: "100%",
      borderRadius: 10,
    },
    sheetOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 35,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingBottom: 0,
    },
    sheetCard: {
      borderRadius: 14,
      borderWidth: 1,
      padding: 16,
      gap: 10,
      shadowColor: "#000",
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 6,
      maxWidth: "92%",
      alignSelf: "center",
    },
    sheetTitle: {
      fontSize: 15,
      fontWeight: "700",
    },
    sheetText: {
      fontSize: 13,
      fontWeight: "500",
      lineHeight: 18,
    },
    sheetBookInfo: {
      paddingVertical: 8,
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: "rgba(0,0,0,0.1)",
      marginVertical: 4,
    },
    sheetBookTitle: {
      fontSize: 14,
      fontWeight: "700",
      marginBottom: 4,
    },
    sheetBookAuthor: {
      fontSize: 12,
      fontWeight: "500",
    },
    sheetActions: {
      flexDirection: "row",
      gap: 10,
      justifyContent: "flex-end",
      marginTop: 4,
    },
    sheetBtn: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
      minWidth: 96,
      alignItems: "center",
    },
    sheetBtnText: {
      fontSize: 13,
      fontWeight: "700",
    },
    datePickerSection: {
      gap: 8,
      marginVertical: 8,
    },
    datePickerLabel: {
      fontSize: 13,
      fontWeight: "600",
    },
    datePickerButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 12,
      borderRadius: 10,
      borderWidth: 1,
    },
    datePickerText: {
      flex: 1,
      fontSize: 14,
      fontWeight: "500",
    },
    datePickerHint: {
      fontSize: 12,
      fontStyle: "italic",
      marginTop: 4,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 20,
    },
    modalContent: {
      borderRadius: 14,
      borderWidth: 1,
      padding: 20,
      width: "100%",
      maxWidth: 400,
      shadowColor: "#000",
      shadowOpacity: 0.2,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 8,
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: "700",
      marginBottom: 16,
      textAlign: "center",
    },
    datePickerIOS: {
      height: 200,
      marginVertical: 10,
    },
    modalActions: {
      flexDirection: "row",
      gap: 10,
      justifyContent: "flex-end",
      marginTop: 16,
    },
    modalBtn: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 10,
      minWidth: 100,
      alignItems: "center",
    },
    modalBtnText: {
      fontSize: 14,
      fontWeight: "700",
    },
    termsSection: {
      marginVertical: 8,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: "rgba(0,0,0,0.1)",
    },
    termsCheckbox: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
    },
    checkbox: {
      width: 20,
      height: 20,
      borderRadius: 4,
      borderWidth: 2,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 2,
    },
    termsText: {
      flex: 1,
      fontSize: 12,
      lineHeight: 18,
    },
    termsLink: {
      fontWeight: "700",
      textDecorationLine: "underline",
    },
  });
