export const mockBooks = [
  {
    title: "All The Light We Cannot See",
    author: "Anthony Doerr",
    status: "available",
    due: null,
  },
  {
    title: "The Girl Who Drank The Moon",
    author: "Kelly Barnhill",
    status: "borrowed",
    due: "06/12/2025",
  },
  {
    title: "Me Before You",
    author: "Jojo Moyes",
    status: "available",
    due: null,
  },
  {
    title: "Pax Journey Home",
    author: "Sara Pennypacker",
    status: "borrowed",
    due: "06/12/2025",
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    status: "available",
    due: null,
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    status: "available",
    due: null,
  },
  {
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt",
    status: "available",
    due: null,
  },
  {
    title: "Clean Code",
    author: "Robert C. Martin",
    status: "borrowed",
    due: "10/12/2025",
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    status: "available",
    due: null,
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    status: "available",
    due: null,
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    status: "borrowed",
    due: "15/12/2025",
  },
  {
    title: "Educated",
    author: "Tara Westover",
    status: "available",
    due: null,
  },
  {
    title: "Becoming",
    author: "Michelle Obama",
    status: "available",
    due: null,
  },
  {
    title: "The Silent Patient",
    author: "Alex Michaelides",
    status: "borrowed",
    due: "20/12/2025",
  },
  {
    title: "Norwegian Wood",
    author: "Haruki Murakami",
    status: "available",
    due: null,
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    status: "available",
    due: null,
  },
  {
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    status: "available",
    due: null,
  },
  {
    title: "The Design of Everyday Things",
    author: "Don Norman",
    status: "available",
    due: null,
  },
];
