export const bookCategories = [
  {
    id: "literature",
    label: "Văn học",
    icon: "book-outline",
    subcategories: [
      { id: "novel", label: "Tiểu thuyết" },
      { id: "short-story", label: "Truyện ngắn" },
      { id: "poetry", label: "Thơ" },
      { id: "horror", label: "Kinh dị " },
      { id: "fantasy", label: " Kỳ ảo " },
      { id: "sci-fi", label: "Khoa học viễn tưởng " },
      { id: "detective", label: "Trinh thám " },
      { id: "romance", label: "Lãng mạn " },
      { id: "adventure", label: "Phiêu lưu" },
      { id: "historical-fiction", label: "Lịch sử hư cấu" },
      { id: "realistic-fiction", label: "Văn học hiện thực" },
      { id: "young-adult", label: "Văn học thiếu niên" },
    ],
  },
  {
    id: "non-fiction",
    label: "Phi hư cấu",
    icon: "earth-outline",
    subcategories: [
      { id: "autobiography", label: " Hồi ký" },
      { id: "biography", label: "Tiểu sử" },
      { id: "history", label: "Lịch sử" },
      { id: "science", label: "Khoa học" },
      { id: "business", label: "Kinh doanh" },
      { id: "life-skills", label: "Kỹ năng sống" },
      { id: "self-development", label: "Phát triển bản thân" },
      { id: "psychology", label: "Tâm lý học" },
      { id: "education", label: "Giáo dục" },
      { id: "politics", label: "Xã hội" },
      { id: "philosophy", label: "Triết học" },
    ],
  },
  {
    id: "children",
    label: "Sách Thiếu nhi",
    icon: "happy-outline",
    subcategories: [
      { id: "children-comic", label: "Truyện tranh thiếu nhi" },
      { id: "fairy-tale", label: "Truyện cổ tích" },
      { id: "fable", label: "Truyện ngụ ngôn" },
      { id: "picture-book", label: "Sách tranh " },
      { id: "children-skills", label: "Sách kỹ năng cho trẻ em" },
      { id: "early-education", label: "Sách giáo dục sớm" },
    ],
  },
  {
    id: "academic",
    label: "Sách Giáo dục & Học thuật",
    icon: "school-outline",
    subcategories: [
      { id: "textbook", label: "Giáo trình" },
      { id: "reference", label: "Sách tham khảo" },
      { id: "exam-prep", label: "Sách luyện thi" },
      { id: "research", label: "Sách nghiên cứu" },
      { id: "monograph", label: "Sách chuyên khảo" },
    ],
  },
  {
    id: "religion",
    label: "Tôn giáo & Tâm linh",
    icon: "leaf-outline",
    subcategories: [
      { id: "religious-texts", label: "Kinh sách tôn giáo" },
      { id: "spirituality", label: "Tâm linh" },
      { id: "meditation", label: "Thiền " },
      { id: "buddhism", label: "Phật học" },
      { id: "christianity", label: "Kitô giáo" },
      { id: "folk-religion", label: "Tín ngưỡng dân gian" },
    ],
  },
  {
    id: "professional",
    label: "Sách Chuyên ngành & Thực hành",
    icon: "construct-outline",
    subcategories: [
      { id: "cooking", label: " Ẩm thực" },
      { id: "art", label: "Nghệ thuật" },
      { id: "music", label: "Âm nhạc" },
      { id: "photography", label: "Nhiếp ảnh" },
      { id: "design", label: "Thiết kế" },
      { id: "architecture", label: "Kiến trúc" },
      { id: "medicine", label: "Y học" },
      { id: "technology", label: "Công nghệ" },
      { id: "economics", label: "Kinh tế" },
      { id: "law", label: "Luật" },
    ],
  },
];
