import { StyleSheet, Platform } from "react-native";

export const createStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingTop: Platform.OS === "ios" ? 50 : 30,
      paddingHorizontal: 16,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.inputBorder + "40",
    },
    headerButton: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
    },
    progressBarContainer: {
      flex: 1,
      alignItems: "center",
      paddingHorizontal: 20,
    },
    progressBar: {
      width: 96,
      height: 8,
      borderRadius: 4,
      overflow: "hidden",
    },
    progressBarFill: {
      height: "100%",
      borderRadius: 4,
    },
    helpText: {
      fontSize: 14,
      fontWeight: "500",
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: 100,
    },
    titleSection: {
      paddingHorizontal: 24,
      paddingTop: 24,
      paddingBottom: 16,
      gap: 8,
    },
    title: {
      fontSize: 24,
      fontWeight: "700",
      lineHeight: 32,
    },
    description: {
      fontSize: 16,
      fontWeight: "400",
      lineHeight: 24,
    },
    categoriesGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      paddingHorizontal: 16,
      paddingBottom: 24,
      gap: 12,
    },
    categoryCard: {
      width: "47%",
      aspectRatio: 1,
      borderRadius: 16,
      borderWidth: 2,
      alignItems: "center",
      justifyContent: "center",
      padding: 24,
      gap: 12,
      position: "relative",
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    checkmarkBadge: {
      position: "absolute",
      top: 12,
      right: 12,
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    categoryIconContainer: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
    },
    categoryLabel: {
      fontSize: 14,
      fontWeight: "500",
      textAlign: "center",
    },
    subcategoriesSection: {
      paddingHorizontal: 16,
      paddingBottom: 24,
      gap: 16,
    },
    subcategoriesContainer: {
      borderRadius: 20,
      boxShadow: "0 0 5px 0 rgba(0, 0, 0, 0.05)",
      shadowColor: "#000",
      shadowOpacity: 0.1,

      padding: 20,
      gap: 12,
    },
    subcategoriesHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    subcategoriesTitle: {
      fontSize: 16,
      fontWeight: "600",
    },
    subcategoriesList: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    subcategoryChip: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      boxShadow: "0 0 5px 0 rgba(0, 0, 0, 0.05)",
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
      gap: 6,
    },
    subcategoryCheckmark: {
      marginRight: 2,
    },
    subcategoryLabel: {
      fontSize: 14,
      fontWeight: "500",
    },
    footerSpacer: {
      height: 20,
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: Platform.OS === "ios" ? 32 : 16,
      borderTopWidth: 1,
      borderTopColor: colors.inputBorder + "40",
      gap: 12,
    },
    continueButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 14,
      borderRadius: 12,
      gap: 8,
      shadowColor: "#000",
      shadowOpacity: 0.15,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
      elevation: 4,
    },
    continueButtonText: {
      fontSize: 16,
      fontWeight: "700",
    },
    skipButton: {
      paddingVertical: 8,
      alignItems: "center",
    },
    skipButtonText: {
      fontSize: 14,
      fontWeight: "500",
    },
  });
