import { StyleSheet, Platform } from "react-native";

export const createStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    topBar: {
      paddingTop: Platform.OS === "ios" ? 50 : 30,
      paddingHorizontal: 12,
      paddingBottom: 20,
      minHeight: Platform.OS === "ios" ? 80 : 60,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    topLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flex: 1,
    },
    searchBox: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.cardBg,
      borderRadius: 20,
      paddingHorizontal: 10,
      paddingVertical: 6,
      flex: 1,
      gap: 6,
    },
    searchInput: {
      flex: 1,
      fontSize: 15,
    },
    dropdownTitle: {
      fontSize: 14,
      fontWeight: "700",
    },
    dropdownItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 6,
    },
    dropdownText: {
      fontSize: 14,
      fontWeight: "500",
    },
    overlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 20,
      justifyContent: "flex-start",
    },
    overlayCard: {
      flex: 1,
      borderRadius: 0,
      backgroundColor: colors.cardBg,
      borderWidth: 0,
      shadowColor: "transparent",
      elevation: 0,
      overflow: "hidden",
    },
    overlayHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      paddingBottom: 10,
      gap: 10,
    },
    backBtn: {
      padding: 6,
    },
    overlaySearchBox: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
      borderWidth: 1,
      borderRadius: 22,
      paddingHorizontal: 12,
      paddingVertical: 8,
      gap: 8,
    },
    overlaySearchInput: {
      flex: 1,
      fontSize: 17,
    },
    overlayList: {
      flex: 1,
    },
    overlayListContent: {
      paddingVertical: 8,
      gap: 4,
    },
    topRight: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingLeft: 4,
    },
    notificationButton: {
      position: "relative",
      padding: 4,
    },
    badge: {
      position: "absolute",
      top: -2,
      right: -2,
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 4,
      borderWidth: 2,
      borderColor: "#FFFFFF",
    },
    badgeText: {
      color: "#FFFFFF",
      fontSize: 10,
      fontWeight: "700",
    },
    content: {
      padding: 16,
      paddingBottom: 180,
      gap: 12,
    },
    card: {
      borderRadius: 14,
      padding: 14,
      borderWidth: 0,
      gap: 8,
      shadowColor: "#000",
      shadowOpacity: 0.08,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    cardTitle: {
      fontSize: 15,
      fontWeight: "700",
    },
    cardText: {
      fontSize: 14,
      fontWeight: "500",
    },
    quickCard: {
      borderRadius: 14,
      paddingVertical: 10,
      paddingHorizontal: 8,
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 1 },
      elevation: 1,
    },
    quickRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 8,
    },
    quickItem: {
      flex: 1,
      alignItems: "center",
      gap: 6,
    },
    quickIcon: {
      width: 42,
      height: 42,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
    },
    quickLabel: {
      fontSize: 12,
      fontWeight: "600",
    },
    statsRow: {
      flexDirection: "row",
      gap: 12,
    },
    statBox: {
      flex: 1,
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      gap: 4,
    },
    statNumber: {
      fontSize: 21,
      fontWeight: "700",
    },
    statLabel: {
      fontSize: 13,
      fontWeight: "600",
    },
    cardHeaderRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 4,
    },
    legendRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    legendDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
    },
    legendText: {
      fontSize: 13,
      fontWeight: "600",
    },
    chartRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-end",
      gap: 12,
      paddingTop: 6,
    },
    chartCol: {
      alignItems: "center",
      justifyContent: "flex-end",
      flex: 1,
      gap: 6,
    },
    barGroup: {
      flexDirection: "row",
      alignItems: "flex-end",
      gap: 4,
    },
    bar: {
      width: 12,
      borderRadius: 4,
    },
    chartLabel: {
      fontSize: 12,
      fontWeight: "600",
    },
    chipsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    chip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 10,
      borderWidth: 1,
    },
    dot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    chipText: {
      fontSize: 13,
      fontWeight: "600",
    },
    readingRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 8,
    },
    readingIcon: {
      width: 36,
      height: 36,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
    },
    readingTitle: {
      fontSize: 14,
      fontWeight: "600",
    },
    progressBar: {
      height: 6,
      borderRadius: 3,
      marginTop: 4,
      overflow: "hidden",
    },
    progressFill: {
      height: "100%",
      borderRadius: 3,
    },
    progressText: {
      fontSize: 12,
      fontWeight: "600",
      minWidth: 40,
      textAlign: "right",
    },
    coversScrollView: {
      marginTop: 8,
    },
    coversRow: {
      flexDirection: "row",
      gap: 12,
      paddingRight: 16,
    },
    coverItem: {
      width: 100,
      alignItems: "center",
      gap: 4,
    },
    coverPlaceholder: {
      width: 100,
      height: 140,
      borderRadius: 8,
      borderWidth: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    coverLabel: {
      fontSize: 12,
      fontWeight: "600",
      textAlign: "center",
      marginTop: 4,
    },
    rewardCard: {
      borderRadius: 14,
      padding: 16,
      gap: 12,
      shadowColor: "#000",
      shadowOpacity: 0.15,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    rewardTitle: {
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 0.5,
      textTransform: "uppercase",
    },
    rewardContent: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
    },
    rewardLeft: {
      flex: 1,
    },
    rewardPoints: {
      fontSize: 32,
      fontWeight: "700",
      letterSpacing: -0.5,
    },
    rewardRight: {
      alignItems: "flex-end",
      gap: 4,
    },
    rewardRankRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    rewardRank: {
      fontSize: 16,
      fontWeight: "700",
    },
    rewardRanking: {
      fontSize: 12,
      fontWeight: "600",
      opacity: 0.9,
    },
    rewardProgressSection: {
      marginTop: 4,
    },
    rewardProgressRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    rewardProgressLabel: {
      fontSize: 13,
      fontWeight: "600",
      minWidth: 120,
    },
    rewardProgressBarContainer: {
      flexDirection: "row",
      height: 8,
      borderRadius: 4,
      overflow: "hidden",
      flex: 1,
      backgroundColor: "rgba(255, 255, 255, 0.3)",
    },
    rewardProgressBar: {
      height: "100%",
    },
    rewardProgressBarRemaining: {
      height: "100%",
    },
    rewardNextPoints: {
      fontSize: 12,
      fontWeight: "600",
      minWidth: 80,
      textAlign: "right",
    },
    forYouSection: {
      gap: 12,
    },
    forYouHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    forYouTitle: {
      fontSize: 17,
      fontWeight: "700",
    },
    forYouViewAll: {
      fontSize: 14,
      fontWeight: "600",
    },
    libraryImageContainer: {
      width: "100%",
      borderRadius: 14,
      overflow: "hidden",
      marginBottom: 12,
    },
    libraryImage: {
      width: "100%",
      height: 180,
      borderRadius: 14,
    },
    roomBookingCard: {
      borderRadius: 14,
      padding: 16,
      gap: 12,
      shadowColor: "#000",
      shadowOpacity: 0.08,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    roomBookingContent: {
      gap: 6,
    },
    roomBookingTitle: {
      fontSize: 16,
      fontWeight: "700",
    },
    roomBookingDescription: {
      fontSize: 13,
      fontWeight: "500",
    },
    coverImage: {
      width: "100%",
      height: 120,
      borderRadius: 8,
      marginBottom: 8,
    },
    coverSubLabel: {
      fontSize: 11,
      fontWeight: "500",
      marginTop: 4,
      textAlign: "center",
    },
    cardSubtitle: {
      fontSize: 12,
      fontWeight: "500",
      marginTop: 4,
    },
    loadingText: {
      fontSize: 14,
      fontWeight: "500",
    },
    emptyText: {
      fontSize: 14,
      fontWeight: "500",
    },
  });
