import { StyleSheet, Platform } from "react-native";

export const createStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    topBar: {
      paddingTop: Platform.OS === "ios" ? 50 : 30,
      paddingHorizontal: 12,
      paddingBottom: 20,
      minHeight: Platform.OS === "ios" ? 80 : 60,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    headerTitle: {
      flex: 1,
      textAlign: "center",
      fontSize: 15,
      fontWeight: "700",
    },
    headerActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    iconBtn: {
      padding: 6,
      minWidth: 32,
      alignItems: "center",
    },
    searchBox: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.cardBg,
      borderRadius: 18,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      gap: 6,
      marginLeft: 8,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
    },
    content: {
      padding: 14,
      paddingBottom: 100,
      gap: 12,
    },
    bookCard: {
      alignItems: "center",
      padding: 14,
      borderRadius: 12,
      borderWidth: 1,
      gap: 8,
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 1 },
      elevation: 1,
    },
    cover: {
      width: 96,
      height: 120,
      borderRadius: 8,
      borderWidth: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    bookTitle: {
      fontSize: 16,
      fontWeight: "700",
      textAlign: "center",
    },
    bookAuthor: {
      fontSize: 13,
      fontWeight: "500",
    },
    tagRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      justifyContent: "center",
    },
    tag: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 999,
      borderWidth: 1,
    },
    tagText: {
      fontSize: 12,
      fontWeight: "700",
    },
    actionRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      justifyContent: "center",
    },
    actionChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 12,
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 1 },
      elevation: 2,
    },
    actionText: {
      fontSize: 13,
      fontWeight: "700",
    },
    sectionCard: {
      borderRadius: 12,
      borderWidth: 1,
      padding: 6,
      gap: 6,
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 1 },
      elevation: 1,
    },
    sectionItem: {
      borderRadius: 10,
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderWidth: 1,
      borderColor: "transparent",
      marginVertical: 2,
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: "700",
    },
    sectionContent: {
      marginTop: 8,
      fontSize: 13,
      fontWeight: "500",
      lineHeight: 18,
    },
    bookMetaCenter: {
      fontSize: 12,
      fontWeight: "600",
      textAlign: "center",
    },
    dueDateContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      marginTop: 4,
    },
    sheetOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 35,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingBottom: 0,
    },
    sheetCard: {
      borderRadius: 14,
      borderWidth: 1,
      padding: 16,
      gap: 10,
      shadowColor: "#000",
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 6,
      maxWidth: "92%",
      alignSelf: "center",
    },
    sheetTitle: {
      fontSize: 15,
      fontWeight: "700",
    },
    sheetText: {
      fontSize: 13,
      fontWeight: "500",
      lineHeight: 18,
    },
    sheetActions: {
      flexDirection: "row",
      gap: 10,
      justifyContent: "flex-end",
      marginTop: 4,
    },
    sheetBtn: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
      minWidth: 96,
      alignItems: "center",
    },
    sheetBtnText: {
      fontSize: 13,
      fontWeight: "700",
    },
    overlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 30,
      justifyContent: "flex-start",
    },
    overlayCard: {
      flex: 1,
      borderRadius: 0,
      backgroundColor: colors.cardBg,
      borderWidth: 0,
      shadowColor: "transparent",
      elevation: 0,
      overflow: "hidden",
    },
    overlayHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      paddingBottom: 10,
      gap: 10,
    },
    overlaySearchBox: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
      borderWidth: 1,
      borderRadius: 22,
      paddingHorizontal: 12,
      paddingVertical: 8,
      gap: 8,
    },
    overlaySearchInput: {
      flex: 1,
      fontSize: 17,
    },
    overlayList: {
      flex: 1,
    },
    overlayListContent: {
      paddingVertical: 8,
      gap: 4,
    },
    dropdownTitle: {
      fontSize: 14,
      fontWeight: "700",
    },
    dropdownItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingVertical: 6,
    },
    dropdownText: {
      fontSize: 14,
      fontWeight: "500",
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 80,
    },
    loadingText: {
      fontSize: 14,
      marginTop: 12,
      fontWeight: "500",
    },
    errorContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 80,
      paddingHorizontal: 40,
    },
    errorText: {
      fontSize: 16,
      fontWeight: "600",
      textAlign: "center",
      marginTop: 16,
      marginBottom: 8,
    },
    retryButton: {
      marginTop: 16,
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    retryButtonText: {
      fontSize: 14,
      fontWeight: "600",
    },
    coverImage: {
      width: "100%",
      height: "100%",
      borderRadius: 8,
    },
    datePickerSection: {
      gap: 8,
      marginVertical: 8,
    },
    datePickerLabel: {
      fontSize: 13,
      fontWeight: "600",
    },
    datePickerButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 12,
      borderRadius: 10,
      borderWidth: 1,
    },
    datePickerText: {
      flex: 1,
      fontSize: 14,
      fontWeight: "500",
    },
    datePickerHint: {
      fontSize: 12,
      fontStyle: "italic",
      marginTop: 4,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 20,
    },
    modalContent: {
      borderRadius: 14,
      borderWidth: 1,
      padding: 20,
      width: "100%",
      maxWidth: 400,
      shadowColor: "#000",
      shadowOpacity: 0.2,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 8,
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: "700",
      marginBottom: 16,
      textAlign: "center",
    },
    datePickerIOS: {
      height: 200,
      marginVertical: 10,
    },
    modalActions: {
      flexDirection: "row",
      gap: 10,
      justifyContent: "flex-end",
      marginTop: 16,
    },
    modalBtn: {
      paddingHorizontal: 20,
      paddingVertical: 10,
      borderRadius: 10,
      minWidth: 100,
      alignItems: "center",
    },
    modalBtnText: {
      fontSize: 14,
      fontWeight: "700",
    },
    termsSection: {
      marginVertical: 8,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: "rgba(0,0,0,0.1)",
    },
    termsCheckbox: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 10,
    },
    checkbox: {
      width: 20,
      height: 20,
      borderRadius: 4,
      borderWidth: 2,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 2,
    },
    termsText: {
      flex: 1,
      fontSize: 12,
      lineHeight: 18,
    },
    termsLink: {
      fontWeight: "700",
      textDecorationLine: "underline",
  },
  // Comments styles
  commentsSection: {
    marginTop: 24,
    gap: 16,
  },
  commentsTitle: {
    fontSize: 18,
    fontWeight: "700",
  },
  commentForm: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    gap: 12,
  },
  commentInput: {
    minHeight: 80,
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    textAlignVertical: "top",
  },
  commentSubmitBtn: {
    alignSelf: "flex-end",
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 80,
  },
  commentSubmitBtnDisabled: {
    opacity: 0.5,
  },
  commentSubmitText: {
    fontSize: 14,
    fontWeight: "600",
  },
  commentsLoading: {
    alignItems: "center",
    paddingVertical: 24,
    gap: 8,
  },
  commentsLoadingText: {
    fontSize: 14,
  },
  commentsEmpty: {
    alignItems: "center",
    paddingVertical: 40,
    gap: 12,
  },
  commentsEmptyText: {
    fontSize: 14,
  },
  commentsList: {
    gap: 16,
  },
  commentItem: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    gap: 12,
  },
  commentHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  commentUserInfo: {
    flexDirection: "row",
    gap: 10,
    flex: 1,
  },
  commentAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  commentUserDetails: {
    flex: 1,
    gap: 4,
  },
  commentUserName: {
    fontSize: 14,
    fontWeight: "600",
  },
  commentDate: {
    fontSize: 12,
  },
  commentActions: {
    flexDirection: "row",
    gap: 8,
  },
  commentActionBtn: {
    padding: 4,
  },
  commentContent: {
    fontSize: 14,
    lineHeight: 20,
  },
  commentEditForm: {
    gap: 12,
  },
  commentEditInput: {
    minHeight: 80,
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    textAlignVertical: "top",
    borderWidth: 1,
  },
  commentEditActions: {
    flexDirection: "row",
    gap: 12,
    justifyContent: "flex-end",
  },
  commentEditBtn: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 80,
  },
  commentEditBtnText: {
    fontSize: 14,
    fontWeight: "600",
  },
  loadMoreCommentsBtn: {
    alignItems: "center",
    paddingVertical: 12,
  },
  loadMoreCommentsText: {
    fontSize: 14,
    fontWeight: "600",
  },
  commentInfoBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 8,
  },
  commentInfoText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
  },
});
