import { StyleSheet, Platform } from "react-native";

export const createStyles = (colors) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingTop: Platform.OS === "ios" ? 50 : 30,
      paddingHorizontal: 16,
      paddingBottom: 16,
      minHeight: Platform.OS === "ios" ? 90 : 70,
      gap: 12,
      shadowColor: "#000",
      shadowOpacity: 0.1,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 4,
    },
    backBtn: {
      padding: 8,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    headerInfo: {
      flex: 1,
      gap: 6,
    },
    headerTitle: {
      fontSize: 17,
      fontWeight: "700",
      letterSpacing: 0.3,
    },
    statusRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    statusDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    statusText: {
      fontSize: 13,
      fontWeight: "500",
      opacity: 0.9,
    },
    callBtn: {
      padding: 10,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    messages: {
      flexGrow: 1,
      paddingHorizontal: 16,
      paddingVertical: 16,
      gap: 12,
    },
    bubbleRow: {
      flexDirection: "row",
      marginBottom: 4,
    },
    bubbleRowMe: {
      justifyContent: "flex-end",
    },
    bubbleRowOther: {
      justifyContent: "flex-start",
    },
    bubble: {
      maxWidth: "75%",
      borderRadius: 18,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderWidth: 0,
      shadowColor: "#000",
      shadowOpacity: 0.08,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 3,
    },
    bubbleText: {
      fontSize: 15,
      fontWeight: "400",
      lineHeight: 20,
    },
    composer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      paddingBottom: Platform.OS === "ios" ? 12 : 16,
      borderTopWidth: 1,
      shadowColor: "#000",
      shadowOpacity: 0.05,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: -2 },
      elevation: 5,
    },
    input: {
      flex: 1,
      fontSize: 15,
      paddingHorizontal: 16,
      paddingVertical: Platform.OS === "ios" ? 12 : 10,
      borderRadius: 24,
      borderWidth: 1,
      maxHeight: 100,
    },
    iconBtn: {
      padding: 8,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    sendBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOpacity: 0.15,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
      elevation: 4,
    },
    loadingText: {
      fontSize: 14,
      marginTop: 8,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 60,
      gap: 20,
    },
    emptyIconContainer: {
      width: 120,
      height: 120,
      borderRadius: 60,
      alignItems: "center",
      justifyContent: "center",
      opacity: 0.5,
    },
    emptyText: {
      fontSize: 15,
      textAlign: "center",
      fontWeight: "500",
      paddingHorizontal: 40,
      lineHeight: 22,
    },
    timeText: {
      fontSize: 11,
      marginTop: 6,
      opacity: 0.75,
      alignSelf: "flex-end",
    },
    typingText: {
      fontSize: 12,
      fontStyle: "italic",
      marginLeft: 6,
      opacity: 0.8,
    },
  });
