export const themes = {
  light: {
    background: '#E5E5E5',
    headerBg: '#2196F3',
    headerText: '#FFFFFF',
    cardBg: '#FFFFFF',
    text: '#333333',
    label: '#333333',
    inputBorder: '#87CEEB',
    inputBg: '#FFFFFF',
    placeholder: '#888888',
    muted: '#666666',
    buttonBg: '#2196F3',
    buttonText: '#FFFFFF',
    outline: '#2196F3',
    error: '#FF0000',
  },
  dark: {
    background: '#121212',
    headerBg: '#1E88E5',
    headerText: '#FFFFFF',
    cardBg: '#1F1F1F',
    text: '#EAEAEA',
    label: '#EAEAEA',
    inputBorder: '#64B5F6',
    inputBg: '#2A2A2A',
    placeholder: '#AAAAAA',
    muted: '#B0B0B0',
    buttonBg: '#2196F3',
    buttonText: '#FFFFFF',
    outline: '#64B5F6',
    error: '#FF6B6B',
  },
};

export const i18n = {
  vi: {
    appTitle: 'QUẢN LÝ THƯ VIỆN',
    uniTitle: 'Đại học Bách Khoa',
    login: 'Đăng nhập',
    register: 'Đăng kí',
    search: 'Tìm kiếm',
    searchHistory: 'Lịch sử tìm kiếm',
    username: 'Tên đăng nhập',
    password: 'Mật khẩu',
    forgotPassword: 'Quên mật khẩu?',
    loginTitle: 'Đăng nhập',
    registerTitle: 'Đăng kí tài khoản',
    reading: 'Đang đọc',
    featured: 'Sách nổi bật',
    monthly: 'Thống kê theo tháng',
    returned: 'Trả',
    quickScan: 'Quét mã',
    quickDownload: 'Tải xuống',
    quickPromo: 'Khuyến mãi',
    quickFavorite: 'Yêu thích',
    email: 'Email',
    phone: 'Số điện thoại',
    accountType: 'Loại tài khoản',
    student: 'Sinh viên',
    teacher: 'Giảng viên',
    studentCode: 'Mã sinh viên',
    teacherCode: 'Mã giảng viên',
    confirmPassword: 'Nhập lại mật khẩu',
    backToLogin: 'Trở về đăng nhập',
    forgotTitle: 'Quên mật khẩu',
    forgotDesc: 'Nhập email hoặc tên đăng nhập của bạn để nhận liên kết đặt lại mật khẩu.',
    forgotSend: 'Gửi yêu cầu',
    sendRequest: 'Gửi yêu cầu',
    themeLabel: 'Giao diện',
    langLabel: 'Ngôn ngữ',
    light: 'Sáng',
    dark: 'Tối',
    vi: 'Tiếng Việt',
    en: 'Tiếng Anh',
    emailExample: 'example@hcmut.edu.vn',
    phonePlaceholder: 'Nhập số điện thoại',
    studentCodePlaceholder: 'Nhập 7 số mã sinh viên',
    teacherCodePlaceholder: 'Nhập mã giảng viên',
    emailError: 'Email phải có đuôi @hcmut.edu.vn',
    studentCodeError: 'Mã sinh viên phải là 7 số',
    settings: 'Cài đặt',
    accountSettings: 'Thiết lập tài khoản',
    editInformation: 'Chỉnh sửa thông tin',
    changePassword: 'Thay đổi mật khẩu',
    enableReturnNotifications: 'Bật thông báo trả sách',
    autoUpdate: 'Tự động cập nhật',
    myBookshelf: 'Tủ sách của tôi',
    aboutUs: 'Về chúng tôi',
    privacyPolicy: 'Chính sách bảo mật',
  },
  en: {
    appTitle: 'LIBRARY MANAGEMENT',
    uniTitle: 'University of Technology',
    login: 'Login',
    register: 'Register',
    search: 'Search',
    searchHistory: 'Search history',
    username: 'Username',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    loginTitle: 'Sign in',
    registerTitle: 'Create an account',
    reading: 'Reading',
    featured: 'Featured books',
    monthly: 'Monthly stats',
    returned: 'Returned',
    quickScan: 'Scan code',
    quickDownload: 'Download',
    quickPromo: 'Promotions',
    quickFavorite: 'Favorite',
    email: 'Email',
    phone: 'Phone number',
    accountType: 'Account type',
    student: 'Student',
    teacher: 'Lecturer',
    studentCode: 'Student ID',
    teacherCode: 'Lecturer ID',
    confirmPassword: 'Confirm password',
    backToLogin: 'Back to login',
    forgotTitle: 'Forgot password',
    forgotDesc: 'Enter your email or username to receive a reset link.',
    forgotSend: 'Send request',
    sendRequest: 'Send request',
    themeLabel: 'Theme',
    langLabel: 'Language',
    light: 'Light',
    dark: 'Dark',
    vi: 'Vietnamese',
    en: 'English',
    emailExample: 'example@hcmut.edu.vn',
    phonePlaceholder: 'Enter phone number',
    studentCodePlaceholder: 'Enter 7-digit student ID',
    teacherCodePlaceholder: 'Enter lecturer ID',
    emailError: 'Email must end with @hcmut.edu.vn',
    studentCodeError: 'Student ID must be 7 digits',
    settings: 'Settings',
    accountSettings: 'Account settings',
    editInformation: 'Edit information',
    changePassword: 'Change password',
    enableReturnNotifications: 'Enable book return notifications',
    autoUpdate: 'Automatic updates',
    myBookshelf: 'My bookshelf',
    aboutUs: 'About us',
    privacyPolicy: 'Privacy policy',
  },
};

export const getThemeStrings = (themeKey = 'light', langKey = 'vi') => {
  const colors = themes[themeKey] || themes.light;
  const strings = i18n[langKey] || i18n.vi;
  return { colors, strings };
};

