export const themes = {
  light: {
    background: '#E5E5E5',
    headerBg: '#2196F3',
    headerText: '#FFFFFF',
    cardBg: '#FFFFFF',
    text: '#333333',
    label: '#333333',
    inputBorder: '#87CEEB',
    inputBg: '#FFFFFF',
    placeholder: '#888888',
    muted: '#666666',
    buttonBg: '#2196F3',
    buttonText: '#FFFFFF',
    outline: '#2196F3',
    error: '#FF0000',
  },
  dark: {
    background: '#121212',
    headerBg: '#1E88E5',
    headerText: '#FFFFFF',
    cardBg: '#1F1F1F',
    text: '#EAEAEA',
    label: '#EAEAEA',
    inputBorder: '#64B5F6',
    inputBg: '#2A2A2A',
    placeholder: '#AAAAAA',
    muted: '#B0B0B0',
    buttonBg: '#2196F3',
    buttonText: '#FFFFFF',
    outline: '#64B5F6',
    error: '#FF6B6B',
  },
};

export const i18n = {
  vi: {
    appTitle: 'QUẢN LÝ THƯ VIỆN',
    uniTitle: 'Đại học Bách Khoa',
    login: 'Đăng nhập',
    register: 'Đăng kí',
    search: 'Tìm kiếm',
    searchHistory: 'Lịch sử tìm kiếm',
    username: 'Tên đăng nhập',
    password: 'Mật khẩu',
    forgotPassword: 'Quên mật khẩu?',
    loginTitle: 'Đăng nhập',
    registerTitle: 'Đăng kí tài khoản',
    reading: 'Đang đọc',
    featured: 'Sách nổi bật',
    monthly: 'Thống kê theo tháng',
    returned: 'Trả',
    quickScan: 'Quét mã',
    quickDownload: 'Tải xuống',
    quickPromo: 'Khuyến mãi',
    quickFavorite: 'Yêu thích',
    email: 'Email',
    phone: 'Số điện thoại',
    accountType: 'Loại tài khoản',
    student: 'Sinh viên',
    teacher: 'Giảng viên',
    studentCode: 'Mã sinh viên',
    teacherCode: 'Mã giảng viên',
    confirmPassword: 'Nhập lại mật khẩu',
    backToLogin: 'Trở về đăng nhập',
    forgotTitle: 'Quên mật khẩu',
    forgotDesc: 'Nhập email hoặc tên đăng nhập của bạn để nhận liên kết đặt lại mật khẩu.',
    forgotSend: 'Gửi yêu cầu',
    sendRequest: 'Gửi yêu cầu',
    themeLabel: 'Giao diện',
    langLabel: 'Ngôn ngữ',
    light: 'Sáng',
    dark: 'Tối',
    vi: 'Tiếng Việt',
    en: 'Tiếng Anh',
    emailExample: 'example@hcmut.edu.vn',
    phonePlaceholder: 'Nhập số điện thoại',
    studentCodePlaceholder: 'Nhập 7 số mã sinh viên',
    teacherCodePlaceholder: 'Nhập mã giảng viên',
    emailError: 'Email phải có đuôi @hcmut.edu.vn',
    studentCodeError: 'Mã sinh viên phải là 7 số',
    settings: 'Cài đặt',
    accountSettings: 'Thiết lập tài khoản',
    editInformation: 'Chỉnh sửa thông tin',
    changePassword: 'Thay đổi mật khẩu',
    enableReturnNotifications: 'Bật thông báo trả sách',
    autoUpdate: 'Tự động cập nhật',
    myBookshelf: 'Tủ sách của tôi',
    aboutUs: 'Về chúng tôi',
    privacyPolicy: 'Chính sách bảo mật',
    personalInformation: 'THÔNG TIN CÁ NHÂN',
    fullName: 'Họ và tên',
    fullNamePlaceholder: 'Họ và tên của bạn',
    dateOfBirth: 'Ngày sinh',
    dateOfBirthPlaceholder: 'Vui lòng chọn ngày sinh',
    gender: 'Giới tính',
    genderPlaceholder: 'Nam/Nữ',
    male: 'Nam',
    female: 'Nữ',
    emailPlaceholder: 'example@hcmut.edu.vn',
    save: 'Lưu',
    datePicker: 'Date Picker',
    cancel: 'Hủy',
    ok: 'OK',
    confirmPassword: 'Xác nhận mật khẩu',
    enterPasswordToSave: 'Vui lòng nhập mật khẩu để lưu thông tin',
    confirm: 'Xác nhận',
    fullNameRequired: 'Vui lòng nhập họ và tên',
    phoneRequired: 'Vui lòng nhập số điện thoại',
    dateOfBirthRequired: 'Vui lòng chọn ngày sinh',
    passwordRequired: 'Vui lòng nhập mật khẩu',
    passwordIncorrect: 'Mật khẩu không đúng',
    success: 'Thành công',
    saveSuccess: 'Đã lưu thông tin thành công',
    error: 'Lỗi',
    changePasswordDescription: 'Vui lòng nhập mật khẩu hiện tại và mật khẩu mới của bạn',
    currentPassword: 'Mật khẩu hiện tại',
    currentPasswordRequired: 'Vui lòng nhập mật khẩu hiện tại',
    currentPasswordPlaceholder: 'Nhập mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    newPasswordRequired: 'Vui lòng nhập mật khẩu mới',
    newPasswordPlaceholder: 'Nhập mật khẩu mới (tối thiểu 6 ký tự)',
    confirmNewPassword: 'Xác nhận mật khẩu mới',
    confirmPasswordRequired: 'Vui lòng xác nhận mật khẩu mới',
    confirmPasswordPlaceholder: 'Nhập lại mật khẩu mới',
    passwordMinLength: 'Mật khẩu phải có ít nhất 6 ký tự',
    passwordNotMatch: 'Mật khẩu xác nhận không khớp',
    passwordSameAsOld: 'Mật khẩu mới phải khác mật khẩu hiện tại',
    passwordChangedSuccess: 'Đã thay đổi mật khẩu thành công',
    verifyIdentity: 'Xác thực danh tính',
    selectVerificationMethod: 'Chọn phương thức xác thực để nhận mã OTP',
    smsVerification: 'Xác thực qua SMS',
    smsVerificationDesc: 'Nhận mã OTP qua tin nhắn SMS',
    emailVerification: 'Xác thực qua Email',
    emailVerificationDesc: 'Nhận mã OTP qua email',
    enterOTP: 'Nhập mã OTP',
    sendOTP: 'Gửi OTP',
    verify: 'Xác nhận',
    otpSent: 'OTP đã được gửi',
    otpSentToPhone: 'Mã OTP đã được gửi đến số điện thoại của bạn',
    otpSentToEmail: 'Mã OTP đã được gửi đến email của bạn',
    otpRequired: 'Vui lòng nhập mã OTP',
    otpInvalid: 'Mã OTP phải có 6 số',
    otpIncorrect: 'Mã OTP không đúng',
    resendOTP: 'Gửi lại mã OTP',
    resendOTPIn: 'Gửi lại mã sau',
  },
  en: {
    appTitle: 'LIBRARY MANAGEMENT',
    uniTitle: 'University of Technology',
    login: 'Login',
    register: 'Register',
    search: 'Search',
    searchHistory: 'Search history',
    username: 'Username',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    loginTitle: 'Sign in',
    registerTitle: 'Create an account',
    reading: 'Reading',
    featured: 'Featured books',
    monthly: 'Monthly stats',
    returned: 'Returned',
    quickScan: 'Scan code',
    quickDownload: 'Download',
    quickPromo: 'Promotions',
    quickFavorite: 'Favorite',
    email: 'Email',
    phone: 'Phone number',
    accountType: 'Account type',
    student: 'Student',
    teacher: 'Lecturer',
    studentCode: 'Student ID',
    teacherCode: 'Lecturer ID',
    confirmPassword: 'Confirm password',
    backToLogin: 'Back to login',
    forgotTitle: 'Forgot password',
    forgotDesc: 'Enter your email or username to receive a reset link.',
    forgotSend: 'Send request',
    sendRequest: 'Send request',
    themeLabel: 'Theme',
    langLabel: 'Language',
    light: 'Light',
    dark: 'Dark',
    vi: 'Vietnamese',
    en: 'English',
    emailExample: 'example@hcmut.edu.vn',
    phonePlaceholder: 'Enter phone number',
    studentCodePlaceholder: 'Enter 7-digit student ID',
    teacherCodePlaceholder: 'Enter lecturer ID',
    emailError: 'Email must end with @hcmut.edu.vn',
    studentCodeError: 'Student ID must be 7 digits',
    settings: 'Settings',
    accountSettings: 'Account settings',
    editInformation: 'Edit information',
    changePassword: 'Change password',
    enableReturnNotifications: 'Enable book return notifications',
    autoUpdate: 'Automatic updates',
    myBookshelf: 'My bookshelf',
    aboutUs: 'About us',
    privacyPolicy: 'Privacy policy',
    personalInformation: 'PERSONAL INFORMATION',
    fullName: 'Full name',
    fullNamePlaceholder: 'Your full name',
    dateOfBirth: 'Date of birth',
    dateOfBirthPlaceholder: 'Please select date of birth',
    gender: 'Gender',
    genderPlaceholder: 'Male/Female',
    male: 'Male',
    female: 'Female',
    emailPlaceholder: 'example@hcmut.edu.vn',
    save: 'Save',
    datePicker: 'Date Picker',
    cancel: 'Cancel',
    ok: 'OK',
    confirmPassword: 'Confirm Password',
    enterPasswordToSave: 'Please enter your password to save information',
    confirm: 'Confirm',
    fullNameRequired: 'Please enter full name',
    phoneRequired: 'Please enter phone number',
    dateOfBirthRequired: 'Please select date of birth',
    passwordRequired: 'Please enter password',
    passwordIncorrect: 'Incorrect password',
    success: 'Success',
    saveSuccess: 'Information saved successfully',
    error: 'Error',
    changePasswordDescription: 'Please enter your current password and new password',
    currentPassword: 'Current password',
    currentPasswordRequired: 'Please enter current password',
    currentPasswordPlaceholder: 'Enter current password',
    newPassword: 'New password',
    newPasswordRequired: 'Please enter new password',
    newPasswordPlaceholder: 'Enter new password (minimum 6 characters)',
    confirmNewPassword: 'Confirm new password',
    confirmPasswordRequired: 'Please confirm new password',
    confirmPasswordPlaceholder: 'Re-enter new password',
    passwordMinLength: 'Password must be at least 6 characters',
    passwordNotMatch: 'Passwords do not match',
    passwordSameAsOld: 'New password must be different from current password',
    passwordChangedSuccess: 'Password changed successfully',
    verifyIdentity: 'Verify Identity',
    selectVerificationMethod: 'Select verification method to receive OTP code',
    smsVerification: 'SMS Verification',
    smsVerificationDesc: 'Receive OTP code via SMS',
    emailVerification: 'Email Verification',
    emailVerificationDesc: 'Receive OTP code via email',
    enterOTP: 'Enter OTP',
    sendOTP: 'Send OTP',
    verify: 'Verify',
    otpSent: 'OTP sent',
    otpSentToPhone: 'OTP code has been sent to your phone number',
    otpSentToEmail: 'OTP code has been sent to your email',
    otpRequired: 'Please enter OTP code',
    otpInvalid: 'OTP must be 6 digits',
    otpIncorrect: 'Incorrect OTP code',
    resendOTP: 'Resend OTP',
    resendOTPIn: 'Resend code in',
  },
};

export const getThemeStrings = (themeKey = 'light', langKey = 'vi') => {
  const colors = themes[themeKey] || themes.light;
  const strings = i18n[langKey] || i18n.vi;
  return { colors, strings };
};

